# Generated by Django 4.0.8 on 2022-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydCdac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField(default='NAN')),
                ('employee_name', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField(default=0, max_length=3)),
                ('place', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['joining_date'],
            },
        ),
    ]
